### ISSUE TITLE
Not sure how to get local files apart from icloud

### ISSUE THREAD

**Issue by prashanthsun9** [jcesarmobile/FilePicker-Phonegap-iOS-Plugin#10]
Hi, every time i try to choose any file the option that is asked to select from is "iCloud" and there is no other option to select the local files, like images inside photos or documents which are not in iCloud, how do i do that?

Please need help,

**Comment by jcesarmobile** [comment]
You can only pick files from apps that are "Document providers" (have a Document provider extension), like One Drive, Google Drive, Documents, etc. If you don't have any app that is a "Document provider" only the iCloud option will appear
