### ISSUE TITLE
Files are not getting displayed

### ISSUE THREAD

**Issue by prashanthsun9** [jcesarmobile/FilePicker-Phonegap-iOS-Plugin#11]
Hi, i have successfully integrated your plugin (i guess), the icloud option opens up that is all, and then nothing shows up inside that icloud window, no files show up i have added all the identifiers still nothing, is there anything that i am doing wrong, please help

**Comment by jcesarmobile** [comment]
Do you have any files on iCloud drive? try uploading an image from a mac that uses the same iCloud account.

**Comment by prashanthsun9** [comment]
Will this plugin only work with the files in iCloud, i though it will pick all the files from my local, photogallery as well

**Comment by jcesarmobile** [comment]
It pick files from any local "Document provider" app.

I already answered you on https://github.com/jcesarmobile/FilePicker-Phonegap-iOS-Plugin/issues/10

Photo gallery app is not a document provider app, but you can use camera plugin to pick files from the gallery.

On iOS Document Providers are the only way to pick files from a device, it's an iOS limitation.
