### ISSUE TITLE
Unable to load doc, docx and similar files

### ISSUE THREAD

**Issue by paweldziura** [jcesarmobile/FilePicker-Phonegap-iOS-Plugin#12]
I was able to select png or rtf files. 
For microsoft document files, the success callback gives the url but the file in not visible in tmp folder.

Simple code:

```
window.FilePicker.pickFile(function(file){
      console.log(file);
    }, function(err){
      console.log(err);
    }, ["public.item", "public.content", "public.data","com.microsoft.word.doc"]);
```

**Comment by jcesarmobile** [comment]
i can't reproduce it, I open the files in inAppBrowser plugin on the success callback and it's opening .doc fines fine picked from google drive or one drive
