### ISSUE TITLE
not working when picked from google drive

### ISSUE THREAD

**Issue by deshpandeshrinath** [jcesarmobile/FilePicker-Phonegap-iOS-Plugin#19]
every time after I choose file from google drive I get errorCallback msg saying canceled,
however i cloud drive returns the path

**Comment by AgNm** [comment]
Hi, 

Did you find the solution for it? I'm also facing same issue

**Comment by deshpandeshrinath** [comment]
Yes. i guess that have solved the issue.. download the latest version and
now its working

**Comment by AgNm** [comment]
latest version of google drive ?

**Comment by AgNm** [comment]
I'm trying to use the plugin for iOS & when I choose Excel sheet from Google Drive, it is getting converted to PDF.

Everything is working fine with iCloud. Do I need to make any change?

**Comment by AgNm** [comment]
I have opened 1 issue, can you please check that as well : https://github.com/jcesarmobile/FilePicker-Phonegap-iOS-Plugin/issues/33

**Comment by jcesarmobile** [comment]
It's working fine now, must be a bug on google drive
