### ISSUE TITLE
not supporting ios9?

### ISSUE THREAD

**Issue by coicoronado** [jcesarmobile/FilePicker-Phonegap-iOS-Plugin#2]
Hello, after doing a research about an ios plugin to choose files in ios this was the best option (only one) that i find, but i tested in my device (ios 9 iphone 5s) and it doesn't display nothing.

My question is if it supports ios 9 update due some of the code snippets that i check over ionic forums claim that it might be supported but wasn't been tested on a device

**Comment by jcesarmobile** [comment]
I've just tested on an iPod touch with iOS 9.1 and worked.

Did you follow the steps including the xcode part?

**Comment by coicoronado** [comment]
yes with the options selected in the image that is displayed in the
prerequisites

2015-10-26 13:52 GMT-06:00 Julio César <notifications@github.com>:

> I've just tested on an iPod touch with iOS 9.1 and worked.
>
> Did you follow the steps including the xcode part?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/jcesarmobile/FilePicker-Phonegap-iOS-Plugin/issues/2#issuecomment-151264057>
> .
>



-- 
"...los hombres fuertes se cuidan a si mismos; pero, los mas fuertes cuidan
a los demas..."

**Comment by coicoronado** [comment]
My bad, it turns out that the plugins wasn't loaded i just checked and all works like a charm

Enviado desde mi iPhone
