### ISSUE TITLE
How to use other documents providers?

### ISSUE THREAD

**Issue by maximshe** [jcesarmobile/FilePicker-Phonegap-iOS-Plugin#22]
Hello,

I'm new in iOS and Cordova, so maybe ask a silly question.

I want to use you plugin and it works for me, but show only iCloud option in popover.

What should be done to add more options in the list? For example, I want to have Photos and iCloud in my app.

**Comment by jcesarmobile** [comment]
It will show all content provider (apps) installed on the device, if there is any, it will only show iCloud. Photos is not a content provider, you will have to use cordova-plugin-camera for getting the Photos.
