### ISSUE TITLE
Intermittent problem picking files using filepicker

### ISSUE THREAD

**Issue by tonyxrmdavidson** [jcesarmobile/FilePicker-Phonegap-iOS-Plugin#24]
Hi 
I am using your FilePicker for an app I am building. 

I followed your instructions on github and have my container set up correctly.
I am using an iPhone 6s running iOS 10.2.1.

 I am getting an intermittent error. Sometimes it works sometimes it doesn't.

My Code:

function buttonYes(){
    FilePicker.isAvailable(function (avail) {
      console.log(avail ? "YES" : "NO");
    });
    window.FilePicker.pickFile(filePickSuccessCallback,filePickErrorCallback);
}

function filePickSuccessCallback(path){
    var fName = path.substr(path.lastIndexOf('/') + 1);
    console.log(fName);
    var fileDir = cordova.file.tempDirectory + 'com.dearle-Inbox/';
    var timestamp = Math.floor(Date.now());
    timestamp = formatTimeStamp(timestamp);
    
    console.log("You picked this file: " + path);
    
        for(j = 0; j < jobs.jobs.length; j++){
            var job = jobs.jobs[j];
            if(job.jobId == jobid){
                console.log('job.jobId :'+ job.jobId + ' jobid : '+ jobid);
                
                if(docUpload.length == 0){
                    docUpload.push({fileName: fName, job: jobid, documentId: documentId, filePath: path});
                    saveDocUpload(docUpload);
                }
                else{
                    var docIsThere = false;
                    for(du = 0; du < docUpload.length; du++){
                        var docForUpload = docUpload[du];
                        if(docForUpload.fileName == fName){
                            docIsThere = true;
                        }
                    }
                    if(!docIsThere){
                        docUpload.push({fileName: fName, job: jobid, documentId: documentId, filePath: path});
                        saveDocUpload(docUpload);
                    }
                }
                
                console.log(docUpload);
                
                if(!job.docUpload || job.docUpload.length == 0){
                    job.docUpload = [];
                    job.docUpload.push({fileName: fName, job: jobid, documentId: documentId, filePath: path});
                    saveJobs(jobs);
                }
                else{
                    var isDocAlreadyThere = false;
                    for(d = 0; d < job.docUpload.length; d++){
                        var doc = job.docUpload[d];
                        if(doc.fileName == fName ){
                            isDocAlreadyThere = true;
                        }
                    }
                    if(!isDocAlreadyThere){
                        job.docUpload.push({fileName: fName, job: jobid, documentId: documentId, filePath: path});
                        saveJobs(jobs);
                    }
                }
            }
        }
    
    window.resolveLocalFileSystemURL(cordova.file.tempDirectory+'com.dearle-Inbox/+fName, function(fileEntry){
        console.log(fileEntry);
    }, function(e){console.log(e);});
}

The output always tells me I have picked a file and have a successful call back.

console log from success callback:
      You picked this file: /private/var/mobile/Containers/Data/Application/A9025397-8E84-4BF8-91AC-DAF42B06E27B/tmp/com.dearle-Inbox/4156345_How_to_get_started.pdf.

This seems to suggest that I have successfully transferred the file.  However when I check for the file using the window.resolveLocalFileSystemURL call I will get 1 of 2 outputs.

1:   I will get a successful callback as it finds the file or

2:  I will get an FILE_NOT_FOUND_ERROR from Cordova-Plugin-File

I have tried various different things, but to no avail. 

Unfortunately I am not an objective C programmer (it baffles me!!).

I would appreciate your help.

**Comment by tonyxrmdavidson** [comment]
On further investigation it seems the issues are with cordova-plugin-file-transfer which seems to have intermittent problems identifying the path supplied in the '/temp/cortainer-indox'. 

Although I haven't solved that issue I made a work around by simply moving the picked file to a directory that file-transfer does recognise consistently and was then able to upload files using file-transfer without errors.

**Comment by jcesarmobile** [comment]
@tonyxrmdavidson is the file-transfer plugin a known issue? (reported on Cordova JIRA).

If not, can you report it on issues.cordova.io?

**Comment by tonyxrmdavidson** [comment]
I don’t think it is a known issue, so yes I will report it.

**Comment by tonyxrmdavidson** [comment]
Issue reported.

https://issues.apache.org/jira/browse/CB-12463

**Comment by jcesarmobile** [comment]
thanks!

**Comment by tonyxrmdavidson** [comment]
JIRA closed this issue and told me to report it here.  They say they wont look at it as it is a 3rd party app.

I have commented that the issues is not with filepicker, but with cordova-plugin-file-transfer.

I have not re-opened it, but I would be happy to try and replicate it in a simple app as opposed to using my clients app, which I am not free to share .  Perhaps you have an example app already prepared demonstrating filepicker that I could adapt to try and replicate the error?

**Comment by Deejo** [comment]
Hi Tony,

I'm facing similar issue and I am new to cordova.

if it is possible than request your to please share your work around.

Regards-
Deejo
