### ISSUE TITLE
File exists, not doing anything (missing entitlements during installation)

### ISSUE THREAD

**Issue by grrrian** [jcesarmobile/FilePicker-Phonegap-iOS-Plugin#25]
During plugin installation i am getting this error

`File exists, not doing anything: MY_PROJECT/platforms/ios/MY_PROJECT/Resources/MY_PROJECT.entitlements`

I ended up adding the entitlements manually in Cordova resource files.

**Comment by fullhdpixel** [comment]
Can you tell us how you did this? What does the entitlements file look like. Im new to iOS.
