### ISSUE TITLE
I am only able to see icloud option to select file after enabling icloud

### ISSUE THREAD

**Issue by arshad104** [jcesarmobile/FilePicker-Phonegap-iOS-Plugin#27]
Hi,

I am using your plugin to pick a file from device but after enabling icloud I can only able to select a file from icloud but can't see any option to select file from device. What will be the fix? Help me to acheive this.

Thanks

**Comment by jcesarmobile** [comment]
The options displayed are based on the apps you have installed that are content providers. If only iCloud is shown is because you don't have any content provider installed. Install apps such us google drive or one drive and they should appear as options.
