### ISSUE TITLE
How to fetch files from mobile storage

### ISSUE THREAD

**Issue by Abhishekl90** [jcesarmobile/FilePicker-Phonegap-iOS-Plugin#30]
Hello,
I am using this plugin, and  I am able to fetch files from the iCloud. But I want to select files from the mobile storage, so how to do this in Ionic 2 .

Thanks

**Comment by jcesarmobile** [comment]
It will display any app installed that is a document provider (google drive, one drive and some others, but you can't really control it), and if you don't have any installed, then only iCloud will be displayed.
