### ISSUE TITLE
If a file browser is installed can users select documents from the phones storage?

### ISSUE THREAD

**Issue by n0490b** [jcesarmobile/FilePicker-Phonegap-iOS-Plugin#34]
If a user installs a file browser (cant name any because I'm an android user) will they be able to select a file from the devices storage?

**Comment by jcesarmobile** [comment]
No, it doesn't work like that on iOS.
If the user installs an app that is a File provider, he will be able to pick files from that app, not from anywhere on the device storage.
If he installs google drive, he would be able to pick files from google drive, if he installs one drive, then one drive will also appear on the list.
