### ISSUE TITLE
Failed to install 'cordova-plugin-filepicker':TypeError: path must be a string or Buffer

### ISSUE THREAD

**Issue by al06** [jcesarmobile/FilePicker-Phonegap-iOS-Plugin#35]
While deploying to ipad facing this issue even in the sample demo application it is failed in deployment with the error mentioned above

**Comment by jcesarmobile** [comment]
How did you install the plugin?
Cordova CLI version?

**Comment by jcesarmobile** [comment]
Try with latest version.
