### ISSUE TITLE
FilePicker.pickFile does not show content providers

### ISSUE THREAD

**Issue by peresbruno** [jcesarmobile/FilePicker-Phonegap-iOS-Plugin#43]
When I run the following code in an iPhone 7 with iOS 11.2.6 no content providers are shown as you can see in the image:

```
FilePicker.pickFile(
	function (uri) {
		deferred.resolve(uri);
	},
	function (error) {
		console.log(error);
		deferred.reject(error);
	}
);
```

![screen shot 2018-03-28 at 2 55 02 pm](https://user-images.githubusercontent.com/1018182/38047306-710db54e-3298-11e8-955b-40f9e6acf81d.png)

The same code works as expected in an iPhone 4S with with iOS 9.3.5. 

Am I forgetting something?

**Edit:** I don't know if it is a relevant detail, but when I execute the above code, xCode console log a message like:

> 2018-03-28 15:03:51.377993-0300 AppName[383:13444] canceled
> 2018-03-28 15:03:53.182583-0300 AppName[383:13444] [App] if we're in the real pre-commit handler we can't actually add any new fences due to CA restriction

**Comment by ricsantos** [comment]
iOS 11 has deprecated the `UIDocumentMenuViewController` with the introduction of the Files app. I will submit a PR that fixes this.

**Comment by jcesarmobile** [comment]
Changed to not show the UIDocumentMenuViewController on iOS 11, will do a patch release tomorrow with the changes.
