### ISSUE TITLE
Popover menu always left 

### ISSUE THREAD

**Issue by nhoctanker** [jcesarmobile/FilePicker-Phonegap-iOS-Plugin#5]
Hi ! i got issue , To day in install your plugin to my project ionic + cordova 
When i click button upload in  IOS 9 , New popover show but it allways left screen .
How to show it where i clicked

**Comment by jcesarmobile** [comment]
Sorry, I don't understand the issue. Can you give more details? adding screenshots might help

**Comment by nhoctanker** [comment]
Please share me your skype 
The screen issue 
http://prntscr.com/9tg569
How to menu show on button " Select File " Or That Menu show Like this ?
http://prntscr.com/9tg5vm
My project run with Cordova 3.9 + ionic 1.1.0
Thank you guy for reply !

**Comment by nhoctanker** [comment]
on ipad AIr

**Comment by jcesarmobile** [comment]
Now you can pass the position of the popover
