### ISSUE TITLE
TypeError: Object(...) is not a function at IOSFilePicker.pickFile

### ISSUE THREAD

**Issue by CoderLFS** [jcesarmobile/FilePicker-Phonegap-iOS-Plugin#59]
i’m developping an Ionic3 App and wants to allow user to upload files from their devices. I’ve got an issue with cordova/phonegap file picker plugin. 
I followed the instructions on the repo and it keeps on throwing me an error :

```
ERROR Error: Uncaught (in promise): TypeError: Object(...) is not a function
TypeError: Object(...) is not a function
    at IOSFilePicker.pickFile (index.js:27)
```

Even using the simplest code which is given in Ionic documentation doesn’t work :

```
import { IOSFilePicker } from '@ionic-native/file-picker/ngx';

constructor(private filePicker: IOSFilePicker) { }

this.filePicker.pickFile()
  .then(uri => console.log(uri))
  .catch(err => console.log('Error', err));
```

Here some additional info about versions :

The plugin has been correctly installed in app.module.ts with the correct ngx path.
ionic framework : 3.9.2
Ionic App Scripts: 3.1.8
Angular Core: 6.0.3
Angular Compiler CLI: 6.0.3
Node: 8.11.3
@ionic-native/file-picker: 5.4.0
rxjs: 6.3.3
typescript: 2.7.2
any idea ?

Thx

**Comment by jcesarmobile** [comment]
Remove the ngx part from the import, as far as I know that’s only for ionic 4, check the ionic 3 docs here
https://ionicframework.com/docs/v3/native/

**Comment by CoderLFS** [comment]
Already tried this and i get this error :

`Typescript Error
Argument of type '{ declarations: (typeof MyApp)[]; imports: (ModuleWithProviders | typeof BrowserModule | typeof H...' is not assignable to parameter of type 'NgModule'. Types of property 'providers' are incompatible. Type '(typeof SplashScreen | typeof Device | typeof FileTransfer | typeof File | typeof Api | typeof Er...' is not assignable to type 'Provider[]'. Type 'typeof SplashScreen | typeof Device | typeof FileTransfer | typeof File | typeof Api | typeof Err...' is not assignable to type 'Provider'. Type 'IOSFilePickerOriginal' is not assignable to type 'Provider'. Type 'IOSFilePickerOriginal' is not assignable to type 'ClassProvider'. Property 'provide' is missing in type 'IOSFilePickerOriginal'.`

When i add the ngx part at least i can build.  When i delete the ngx part, i can't even build anymore.

**Comment by jcesarmobile** [comment]
You probably also need to use @ionic-native 4.x.x and @ionic-native/file-picker 4.x.x

**Comment by CoderLFS** [comment]
Did this and it worked ! 
Actually building with Ionic pro to test on an iPhone SE.   
I'll let you know if everything goes right.

Thank you

(edit: it works perfectly)
