### ISSUE TITLE
npm/Phonegap build?

### ISSUE THREAD

**Issue by darkdante83** [jcesarmobile/FilePicker-Phonegap-iOS-Plugin#6]
I love your plugin on the local phonegap. But unfortunately i can't use it on phonegap build. Could you consider posting this on npm the cordova plugin site?

**Comment by jcesarmobile** [comment]
I'm going to publish it on npm, but it won't work on phonegap build, because the plugin needs a hook to add the app entitlements, and hooks don't run on phonegap build

**Comment by darkdante83** [comment]
I did not know that! Thx for the answer, i will continue with the offline phonegap. Again: great plugin and thx for all the awesome work

**Comment by jcesarmobile** [comment]
Thanks
I'll try to update the readme and publish the plugin on NPM this weekend.

**Comment by MadMaxedy** [comment]
@jcesarmobile Thx for creating this plugin +1! ! Did you manage to publish it on NPM already? I can't find it.
