### ISSUE TITLE
how to use two mime type,inside pickfile method in ionic4

### ISSUE THREAD

**Issue by 08Thug** [jcesarmobile/FilePicker-Phonegap-iOS-Plugin#63]
I am using this plugin to allow the user to pick only pdf,docx,ppt,txt format ,with using "public.composite-content" ican allow all three except txt, so i have to use public.text how to use both mime type inside the method any help from the creator!?

**Comment by jcesarmobile** [comment]
The utis allows an array, so you'll need "public.composite-content"  and another one for txt, not sure what's the uti for it.

**Comment by 08Thug** [comment]
Found a solution so i am closing the issue

**Comment by 08Thug** [comment]
> The utis allows an array, so you'll need "public.composite-content" and another one for txt, not sure what's the uti for it.

Well thank you passed using array
