### ISSUE TITLE
Choose Local files images

### ISSUE THREAD

**Issue by dhanasekaranv** [jcesarmobile/FilePicker-Phonegap-iOS-Plugin#9]
Hi any one suggest solution for the below issue. when i am using this plugin i can only accessing files from icloud, googleDrive. if there is any way to access the files and images from phone memory.

**Comment by kevin-sharktek** [comment]
It would be great to be able to access local image files from Photos, if possible.

**Comment by jcesarmobile** [comment]
To access photos you have to use the camera plugin, this plugin only allows to pick files from content providers and photos app isn't a content provider
